https://numpy.org/doc/stable/

In [1]:
import numpy as np

In [2]:
test_arr = np.array([1,2,3])

In [3]:
test_arr

array([1, 2, 3])

In [4]:
test_arr + 3

array([4, 5, 6])

In [5]:
test_arr**2

array([1, 4, 9])

In [6]:
test_arr + [3, 4]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [7]:
test_arr + [3, 4, 5]

array([4, 6, 8])

In [8]:
test_arr = np.arange(0,100)
test_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
test_arr = np.arange(0,100, 0.5)
test_arr

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [10]:
test_arr +2

array([  2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,   6. ,
         6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5,
        11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5,  15. ,
        15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,  19. ,  19.5,
        20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,  23.5,  24. ,
        24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5,  28. ,  28.5,
        29. ,  29.5,  30. ,  30.5,  31. ,  31.5,  32. ,  32.5,  33. ,
        33.5,  34. ,  34.5,  35. ,  35.5,  36. ,  36.5,  37. ,  37.5,
        38. ,  38.5,  39. ,  39.5,  40. ,  40.5,  41. ,  41.5,  42. ,
        42.5,  43. ,  43.5,  44. ,  44.5,  45. ,  45.5,  46. ,  46.5,
        47. ,  47.5,  48. ,  48.5,  49. ,  49.5,  50. ,  50.5,  51. ,
        51.5,  52. ,  52.5,  53. ,  53.5,  54. ,  54.5,  55. ,  55.5,
        56. ,  56.5,  57. ,  57.5,  58. ,  58.5,  59. ,  59.5,  60. ,
        60.5,  61. ,  61.5,  62. ,  62.5,  63. ,  63.5,  64. ,  64.5,
        65. ,  65.5,

In [11]:
test_arr**2

array([0.00000e+00, 2.50000e-01, 1.00000e+00, 2.25000e+00, 4.00000e+00,
       6.25000e+00, 9.00000e+00, 1.22500e+01, 1.60000e+01, 2.02500e+01,
       2.50000e+01, 3.02500e+01, 3.60000e+01, 4.22500e+01, 4.90000e+01,
       5.62500e+01, 6.40000e+01, 7.22500e+01, 8.10000e+01, 9.02500e+01,
       1.00000e+02, 1.10250e+02, 1.21000e+02, 1.32250e+02, 1.44000e+02,
       1.56250e+02, 1.69000e+02, 1.82250e+02, 1.96000e+02, 2.10250e+02,
       2.25000e+02, 2.40250e+02, 2.56000e+02, 2.72250e+02, 2.89000e+02,
       3.06250e+02, 3.24000e+02, 3.42250e+02, 3.61000e+02, 3.80250e+02,
       4.00000e+02, 4.20250e+02, 4.41000e+02, 4.62250e+02, 4.84000e+02,
       5.06250e+02, 5.29000e+02, 5.52250e+02, 5.76000e+02, 6.00250e+02,
       6.25000e+02, 6.50250e+02, 6.76000e+02, 7.02250e+02, 7.29000e+02,
       7.56250e+02, 7.84000e+02, 8.12250e+02, 8.41000e+02, 8.70250e+02,
       9.00000e+02, 9.30250e+02, 9.61000e+02, 9.92250e+02, 1.02400e+03,
       1.05625e+03, 1.08900e+03, 1.12225e+03, 1.15600e+03, 1.190

In [12]:
test_arr = np.zeros((20,20))
test_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [13]:
test_arr.shape

(20, 20)

In [14]:
test_arr.size

400

In [15]:
test_arr = np.array([2,'a', 5])

In [16]:
test_arr

array(['2', 'a', '5'], dtype='<U21')

In [17]:
test_arr+3

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [18]:
test_arr+"3"

array(['23', 'a3', '53'], dtype='<U22')

In [33]:
test_arr_1 = np.arange(0,10)
test_arr_2 = np.linspace(30, 40, 5)

In [34]:
test_arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
test_arr_2

array([30. , 32.5, 35. , 37.5, 40. ])

In [36]:
np.concat([test_arr_1, test_arr_2])

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 30. ,
       32.5, 35. , 37.5, 40. ])

In [37]:
test_arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
test_arr_2

array([30. , 32.5, 35. , 37.5, 40. ])

In [39]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7,8]])
np.concatenate((x, y), axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [42]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [np.nan, np.nan]])
np.concatenate((x, y), axis=1)


array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4., nan, nan]])